import React from "react";
import './MainSass/index_main.css';

export default function Home(){
    return(
        <div className="Home">
            <h3>Home</h3>
            <p>lorem Bienvenue sur Ipsum.one, votre complice idéal dans la création de faux-texte Lorem Ipsum. Destiné aux graphistes, maquettistes, designers et professionnels de la PAO, notre générateur de texte offre une solution rapide et intuitive pour générer du contenu fictif. Que votre projet concerne la mise en forme de documents imprimés, la création de maquettes pour des sites internet, ou la composition de supports de communication, l’outil fournit un texte standardisé, facilitant la concentration sur l'aspect visuel plutôt que le contenu. Avec un simple clic, générez des paragraphes, des listes ou des mots en Lorem Ipsum, ce texte de remplissage professionnel qui trouve ses racines dans l'histoire de la typographie et du design graphique depuis le 16ème siècle. Découvrez comment notre générateur peut être un atout précieux pour votre processus créatif et vos rendus de maquettes.</p>
            <p>lorem Bienvenue sur Ipsum.one, votre complice idéal dans la création de faux-texte Lorem Ipsum. Destiné aux graphistes, maquettistes, designers et professionnels de la PAO, notre générateur de texte offre une solution rapide et intuitive pour générer du contenu fictif. Que votre projet concerne la mise en forme de documents imprimés, la création de maquettes pour des sites internet, ou la composition de supports de communication, l’outil fournit un texte standardisé, facilitant la concentration sur l'aspect visuel plutôt que le contenu. Avec un simple clic, générez des paragraphes, des listes ou des mots en Lorem Ipsum, ce texte de remplissage professionnel qui trouve ses racines dans l'histoire de la typographie et du design graphique depuis le 16ème siècle. Découvrez comment notre générateur peut être un atout précieux pour votre processus créatif et vos rendus de maquettes.</p>
            <p>lorem Bienvenue sur Ipsum.one, votre complice idéal dans la création de faux-texte Lorem Ipsum. Destiné aux graphistes, maquettistes, designers et professionnels de la PAO, notre générateur de texte offre une solution rapide et intuitive pour générer du contenu fictif. Que votre projet concerne la mise en forme de documents imprimés, la création de maquettes pour des sites internet, ou la composition de supports de communication, l’outil fournit un texte standardisé, facilitant la concentration sur l'aspect visuel plutôt que le contenu. Avec un simple clic, générez des paragraphes, des listes ou des mots en Lorem Ipsum, ce texte de remplissage professionnel qui trouve ses racines dans l'histoire de la typographie et du design graphique depuis le 16ème siècle. Découvrez comment notre générateur peut être un atout précieux pour votre processus créatif et vos rendus de maquettes.</p>
            <p>lorem Bienvenue sur Ipsum.one, votre complice idéal dans la création de faux-texte Lorem Ipsum. Destiné aux graphistes, maquettistes, designers et professionnels de la PAO, notre générateur de texte offre une solution rapide et intuitive pour générer du contenu fictif. Que votre projet concerne la mise en forme de documents imprimés, la création de maquettes pour des sites internet, ou la composition de supports de communication, l’outil fournit un texte standardisé, facilitant la concentration sur l'aspect visuel plutôt que le contenu. Avec un simple clic, générez des paragraphes, des listes ou des mots en Lorem Ipsum, ce texte de remplissage professionnel qui trouve ses racines dans l'histoire de la typographie et du design graphique depuis le 16ème siècle. Découvrez comment notre générateur peut être un atout précieux pour votre processus créatif et vos rendus de maquettes.</p>
            <p>lorem Bienvenue sur Ipsum.one, votre complice idéal dans la création de faux-texte Lorem Ipsum. Destiné aux graphistes, maquettistes, designers et professionnels de la PAO, notre générateur de texte offre une solution rapide et intuitive pour générer du contenu fictif. Que votre projet concerne la mise en forme de documents imprimés, la création de maquettes pour des sites internet, ou la composition de supports de communication, l’outil fournit un texte standardisé, facilitant la concentration sur l'aspect visuel plutôt que le contenu. Avec un simple clic, générez des paragraphes, des listes ou des mots en Lorem Ipsum, ce texte de remplissage professionnel qui trouve ses racines dans l'histoire de la typographie et du design graphique depuis le 16ème siècle. Découvrez comment notre générateur peut être un atout précieux pour votre processus créatif et vos rendus de maquettes.</p>
        </div>
    )
}
