name: First Configuration of GitHub Action Workflow

# Events that trigger the workflow
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo "Hello, world!"
        
      # Runs a set of commands using the runner's shell
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

      # Cache node modules to speed up subsequent runs
      - name: Cache node modules
        uses: actions/cache@v2
        env: 
          cache-name: cache-node-modules
        with: 
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      # Upload a build artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          # Artifact name
          name: artifact
          # A file, directory, or wildcard pattern that describes what to upload
          path: build/
          # The desired behavior if no files are found using the provided path
          if-no-files-found: warn
          # Duration after which artifact will expire in days
          retention-days: 0
          # The level of compression for Zlib to be applied to the artifact archive
          # Value can range from 0 to 9 (0 = No compression, 9 = Best compression)
          # Higher levels result in better compression but take longer to complete
          compression-level: 6
        
      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build
        run: npm run build
          
      # Run tests
      - name: Test
        run: npm test
        
  # deployment configuration to deploy my-project
  pages-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Publish site
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2